name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: kenchan0130/actions-system-info@master
        id: system-info
      - name: Check outputs
        run: |
          OUTPUTS=(
            "OS: ${{ steps.system-info.outputs.os }}"
            "CPU: ${{ steps.system-info.outputs.cpu }}"
            "Memory: ${{ steps.system-info.outputs.memory }}" 
          )
