name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: kenchan0130/actions-system-info@master
        id: system-info
      - name: Check outputs
        run: |
          OUTPUTS=(
            "OS: ${{ steps.system-info.outputs.os }}"
            "CPU: ${{ steps.system-info.outputs.cpu }}"
            "Memory: ${{ steps.system-info.outputs.memory }}"
            "Disk: ${{ steps.system-info.outputs.disk }}"
            "Uptime: ${{ steps.system-info.outputs.uptime }}"
            "Virtualization: ${{ steps.system-info.outputs.virtualization }}"
            "Shell: ${{ steps.system-info.outputs.shell }}"
          )
          for OUTPUT in "${OUTPUTS[@]}"; do
            echo "$OUTPUT"
          done
